name: music
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  flutter_secure_storage: ^9.0.0
  connectivity: ^3.0.3
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
      - family: NovaSquare
        fonts:
           - asset: fonts/NovaSquare.ttf
